In [ ]:
Consider the below code to answer further questions:


import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
to print the data types of both the variables.

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and 
arra_list.

In [3]:
list_ = [1, 2, 3, 'four', 'five']
arra_list = np.array([1, 2, 3, 'four', 'five'])

for i in list_:
    print(type(i))

for j in arra_list:
    print(type(j))


<class 'int'>
<class 'int'>
<class 'int'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and 
arra_list? If so then print the data types of each and every element present in both the variables, list_ 
and arra_list.
Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [5]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data types in list_:")
for elem in list_:
    print(type(elem))

print("\nData types in array_list:")
for elem in array_list:
    print(type(elem))


Data types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [7]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Shape
shape_of_num_array = num_array.shape
print("Shape of num_array:", shape_of_num_array)

# (ii) Size
size_of_num_array = num_array.size
print("Size of num_array:", size_of_num_array)


Shape of num_array: (2, 3)
Size of num_array: 6


In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [8]:
import numpy as np
zero_matrix = np.zeros((3, 3))

print("Array with zeros:")
print(zero_matrix)


Array with zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [9]:
import numpy as np

identity_matrix = np.eye(5)

print("Identity Matrix:")
print(identity_matrix)


Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
